### ISSUE TITLE
Support for new "gpt-4o" tiktoken tokenizer

### ISSUE THREAD

**Issue by gtoubassi** [IAPark/tiktoken_ruby#36]
I may take a run at it myself but happy to "buy someone a coffee" if they beat me to it :).  Curious if there are any potential pitfalls.

**Comment by IAPark** [comment]
Looks like @CaffeeLake did this. Let me know if it doesn't work for you now

**Comment by gtoubassi** [comment]
@CaffeeLake thank you!!!!
